agiosaude/accounts/urls.py
from django.urls import path
from agiosaude.accounts import views as acc_view
from django.contrib.auth import views as auth_view

urlpatterns = [
    path('', auth_view.LoginView.as_view(template_name='login.html'), name='login'),
    path('sair/', auth_view.LogoutView.as_view(next_page='core:home'), name='logout'),
    path('usuario/', acc_view.Usuario_Main, name='usuario_main'),
    path('usuario/novo', acc_view.usuario_nov, name='usuario_nov'),
    path('hospital/', acc_view.edit, name='hospital')
]

agiosaude/core/urls.py
from django.urls import path
from agiosaude.core import views


urlpatterns = [
    path('', views.home, name='home'),
    path('cadastro/', views.cadastro_main, name='cadastro_main'),
    path('cadastro/parciente/novo/', views.cadastro_par, name='cadastro_par'),
    path('cadastro/medico/novo/', views.cadastro_med, name='cadastro_med'),
    path('atendimento/', views.atendimento_main, name='atendimento_main'),
    path('atendimento/novo/', views.atendimento_nov, name='atendimento_nov'),
    path('consulta/', views.consulta_main, name='consulta_main'),
    path('ambulatorio/', views.ambulatorio_main, name='ambulatorio_main'),
    path('consulta/eduardo_paiva', views.consulta_par, name='consulta_par'),
    path('resgistro/atendimento', views.registro_ate, name='registro_ate'),
    path('resgistro/exame', views.registro_exa, name='registro_exa'),
]

agiosaude/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('agiosaude.core.urls', 'core'), namespace='core')),
    path('login/', include(('agiosaude.accounts.urls', 'accounts'), namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agiosaude/core/models.py
from django.db import models


class Hospital(models.Model):
    uf_choiche = (
        ('AC', 'Acre'),
        ('AL', 'Alagoas'),
        ('AP', 'Amapá'),
        ('AM', 'Amazonas'),
        ('BA', 'Bahia'),
        ('CE', 'Ceará'),
        ('DF', 'Distrito Federal'),
        ('ES', 'Espírito Santo'),
        ('GO', 'Goiás'),
        ('MA', 'Maranhão'),
        ('MT', 'Mato Grosso'),
        ('MS', 'Mato Grosso do Sul'),
        ('MG', 'Minas Gerais'),
        ('PA', 'Pará'),
        ('PB', 'Paraíba'),
        ('PR', 'Paraná'),
        ('PE', 'Pernambuco'),
        ('PI', 'Piauí'),
        ('RJ', 'Rio de Janeiro'),
        ('RN', 'Rio Grande do Norte'),
        ('RS', 'Rio Grande do Sul'),
        ('RO', 'Rondônia'),
        ('RR', 'Roraima'),
        ('SC', 'Santa Catarina'),
        ('SP', 'São Paulo'),
        ('SE', 'Sergipe'),
        ('TO', 'Tocantins'),
    )
    razao = models.CharField('Razão Social', max_length=100)
    fantasia = models.CharField('Nome Fantasia', max_length=100, null=True, blank=True)
    cnpj = models.IntegerField('CNPJ', null=True, blank=True)
    logo = models.ImageField(verbose_name='Logomarca', null=True, blank=True)
    cep = models.IntegerField('CEP')
    logradouro = models.CharField('Logradouro', max_length=200)
    num_end = models.IntegerField('Numero', null=True, blank=True)
    bairro = models.CharField('Bairro', max_length=100)
    municipio = models.CharField('Municipio', max_length=100)
    uf = models.CharField('UF', choices=uf_choiche, max_length=2)
    cnes = models.IntegerField('CNES')


class Paciente(models.Model):
    sexo_choiche = (
        ('M', 'Masculino'),
        ('F', 'Feminino'),
    )
    uf_choiche = (
        ('AC', 'Acre'),
        ('AL', 'Alagoas'),
        ('AP', 'Amapá'),
        ('AM', 'Amazonas'),
        ('BA', 'Bahia'),
        ('CE', 'Ceará'),
        ('DF', 'Distrito Federal'),
        ('ES', 'Espírito Santo'),
        ('GO', 'Goiás'),
        ('MA', 'Maranhão'),
        ('MT', 'Mato Grosso'),
        ('MS', 'Mato Grosso do Sul'),
        ('MG', 'Minas Gerais'),
        ('PA', 'Pará'),
        ('PB', 'Paraíba'),
        ('PR', 'Paraná'),
        ('PE', 'Pernambuco'),
        ('PI', 'Piauí'),
        ('RJ', 'Rio de Janeiro'),
        ('RN', 'Rio Grande do Norte'),
        ('RS', 'Rio Grande do Sul'),
        ('RO', 'Rondônia'),
        ('RR', 'Roraima'),
        ('SC', 'Santa Catarina'),
        ('SP', 'São Paulo'),
        ('SE', 'Sergipe'),
        ('TO', 'Tocantins'),
    )
    raca_choiche = (
        ('BA', 'Branca'),
        ('NE', 'Negro'),
        ('AM', 'Amarela'),
        ('PA', 'Parda'),
        ('IN', 'Indígena'),
        ('OU', 'Outra'),
        ('ND', 'Não Declarado'),
    )
    name = models.CharField('Nome', max_length=100)
    rg = models.IntegerField('RG', null=True, blank=True)
    uf_nas = models.CharField('UF', choices=uf_choiche, max_length=2, null=True, blank=True)
    pai = models.CharField('Pai', max_length=100, blank=True, null=True)
    mae = models.CharField('Mãe', max_length=100, blank=True, null=True)
    slug = models.SlugField('Atalho')
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    foto = models.ImageField(upload_to='', verbose_name='Foto', null=True, blank=True)
    cpf = models.IntegerField('CPF', null=True, blank=True)
    nascimento = models.DateField('Nascimento')
    sexo = models.CharField('Sexo', choices=sexo_choiche, max_length=1)
    profissao = models.CharField('Profissão', max_length=100, blank=True, null=True)
    telefone = models.IntegerField('Contato', null=True, blank=True)
    cep = models.IntegerField('CEP', null=True, blank=True)
    logradouro = models.CharField('Logradouro', max_length=100, blank=True, null=True)
    bairro = models.CharField('Logradouro', max_length=100, blank=True, null=True)
    municipio = models.CharField('Municipio', max_length=100, blank=True, null=True)
    uf_end = models.CharField('UF', choices=uf_choiche, max_length=2)
    ibge = models.IntegerField('IBGE', null=True, blank=True)
    raca = models.CharField('Raça', choices=raca_choiche, max_length=2)
    etnia = models.CharField('Etnia', max_length=50, blank=True, null=True)

    class Meta:
        verbose_name = 'Paciente'
        verbose_name_plural = 'Pacientes'
        ordering = ['name']


class Funcionario(models.Model):
    sexo_choiche = (
        ('M', 'Masculino'),
        ('F', 'Feminino'),
    )
    fun_choiche = (
        ('M', 'Médico'),
        ('A', 'Atendente'),
        ('E', 'Enfermeiro'),
        ('F', 'Farmaceutico'),
    )
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Atalho')
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    foto = models.ImageField(upload_to='', verbose_name='Foto', null=True, blank=True)
    cpf = models.IntegerField('CPF', null=True, blank=True)
    nascimento = models.DateField('Nascimento', null=True, blank=True)
    sexo = models.CharField('Sexo', choices=sexo_choiche, max_length=1)
    funcao = models.CharField('Função', choices=fun_choiche, max_length=1)
    profissao = models.CharField('Profissão', max_length=100, null=True, blank=True)

    class Meta:
        verbose_name = 'Funcionário'
        verbose_name_plural = 'Funcionários'
        ordering = ['name']


class Medicamento(models.Model):
    name = models.CharField('Nome', max_length=100)
    description = models.TextField('Descrição', blank=True)
    slug = models.SlugField('Atalho')
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    quatidade = models.IntegerField('Quatidade')

    class Meta:
        verbose_name = 'Medicamento'
        verbose_name_plural = 'Medicamentos'
        ordering = ['name']


class Laudo(models.Model):
    description = models.TextField('Descrição', blank=True)
    slug = models.SlugField('Atalho')
    paciente = models.ForeignKey(Paciente, verbose_name='Paciente', on_delete=models.CASCADE, related_name='laudo_par')
    funcionario = models.ForeignKey(Funcionario, verbose_name='Funcionário', on_delete=models.CASCADE, related_name='laudo_fun')

    class Meta:
        verbose_name = 'Laudo'
        verbose_name_plural = 'Laudos'
        ordering = ['paciente']


class Atendimento(models.Model):
    cla_choiche = (
        ('AZ', 'Azul'),
        ('VD', 'Verde'),
        ('AM', 'Amarelo'),
        ('VM', 'Vermelho'),
    )
    trazido_choiche = (
        ('CP', 'Condução Própria'),
        ('AM', 'Ambulância'),
        ('SB', 'Samu/Bombeiro'),
        ('PV', 'Policiais e Viaturas'),
    )
    ficha = models.IntegerField('Ficha')
    classificacao = models.CharField('Classificação', choices=cla_choiche, max_length=2)
    senha = models.IntegerField('Senha', null=True, blank=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    termino = models.DateTimeField('Término', null=True, blank=True)
    paciente = models.ForeignKey(Paciente, verbose_name='Paciente', on_delete=models.CASCADE, related_name='ate_par')
    funcionario = models.ForeignKey(Funcionario, verbose_name='Funcionário', on_delete=models.CASCADE, related_name='ate_fun')
    primeiro = models.BooleanField('Primeiro Atendimento')
    acidente_trab = models.BooleanField('Acidente de trabalho')
    trazido = models.CharField('Trazido por', choices=trazido_choiche, max_length=1)
    acompanhante = models.CharField('Acompanhante', max_length=100, null=True, blank=True)
    placa = models.CharField('Placa da Viatura', max_length=20, null=True, blank=True)
    pressao = models.CharField('Pressão Arterial', max_length=20, null=True, blank=True)
    temperatura =  models.IntegerField('Temperatura', null=True, blank=True)
    peso = models.IntegerField('Peso', blank=True, null=True)
    altura = models.IntegerField('Peso', blank=True, null=True)
    dextro = models.BooleanField('Dextro')
    descricao = models.TextField('Descrição', null=True, blank=True)
    hipotese = models.TextField('Hipótese Diagnostica', null=True, blank=True)
    conduta = models.TextField('Condulta', null=True, blank=True)
    anotacoes = models.TextField('Anotações', null=True, blank=True)


class Procedimento(models.Model):
    atendimento = models.ForeignKey(Atendimento, verbose_name='Atendimento', on_delete=models.CASCADE, related_name='pro_atende')
    procedimento = models.IntegerField('Procedimento')
    quantidade = models.IntegerField('Quantidade')
    cbo = models.IntegerField('CBO', null=True, blank=True)
    cid = models.IntegerField('CID', null=True, blank=True)
    carater_atend = models.IntegerField('Carater Atendimento', null=True, blank=True)
    autorizacao = models.IntegerField('Número Autorização', null=True, blank=True)


class Exame(models.Model):
    atendimento = models.ForeignKey(Atendimento, verbose_name='Atendimento', on_delete=models.CASCADE, related_name='exa_atende')
    descricao = models.TextField('Descrição')
    data = models.DateField ('Data de entrega', null=True, blank=True)
    realizado = models.BooleanField('Concluido')
    resultado = models.TextField('Resultado', null=True, blank=True)
    anexo = models.FileField(upload_to='core/static/arq', blank=True, null=True)
    # anexo = models.TextField('File', blank=True)

agiosaude/core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def home(request):
    return render(request, 'home.html')

@login_required
def cadastro_main(request):
    return render(request, 'cadastro_main.html')

@login_required
def cadastro_par(request):
    return render(request, 'cadastro_par.html')

@login_required
def cadastro_med(request):
    return render(request, 'cadastro_med.html')

@login_required
def atendimento_main(request):
    return render(request, 'atendimento_main.html')

@login_required
def atendimento_nov(request):
    return render(request, 'atendimento_nov.html')

@login_required
def consulta_main(request):
    return render(request, 'consulta_main.html')

@login_required
def ambulatorio_main(request):
    return render(request, 'ambulatorio_main.html')

@login_required
def consulta_par(request):
    return render(request, 'consulta_par.html')

@login_required
def registro_ate(request):
    return render(request, 'registro_ate.html')

@login_required
def registro_exa(request):
    return render(request, 'registro_exa.html')

agiosaude/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Sistema de Saude{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/pure-min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="stylesheet" href="{% static 'css/all.css' %}" />
</head>
<body>
{% block home %}{% endblock %}
<div class="content">
    {% if messages %}
        <div class="pure-g-r content-ribbon">
            <aside class="pure-u-1">
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            </aside>
        </div>
    {% endif %}
    {% block content %}{% endblock %}
    <div class="footer">
        SIMED - Sistema de Gestão Hospitalar
    </div>
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="https://unpkg.com/popper.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

agiosaude/core/templates/cadastro_main.html
{% extends 'home.html' %}
{% load static %}

{% block content %}
    <div class="content-main " id="content-main">
        <!-- ############ Main START-->
        <div class="padding">
            <div class="box">
                <section class="content-header">

                    <div class="box-header">
                        <h3>Médico</h3>
                    </div>
                    <div class="p-3">
                        <div class="row" >
                            <div class="col-md-5">
                                <a href="{% url 'core:cadastro_med' %}" type="button" class="btn btn-fw primary">Novo</a>
                            </div>
                            <div class="col-sm-4">
                            </div>
                            <div class="col-sm-3">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Busca" style="background: none;margin: -3px 5px 0px 0px;">
                                    <span class="input-group-btn">
              <button class="btn white" type="button">Go!</button>
            </span>
                                </div>
                            </div>
                        </div>
                    </div>

                </section>
                <!-- Main content -->
                <section class="content" style="padding-top: 0">
                    <div id="main-wrapper">
                        <div class="col-lg-12 col-md-12">
                            <div class="panel panel-white">
                                <div class="panel-body">
                                    <div class="">
                                        <table id="example" class="display table bootstrap-grid" style="width: 100%;">
                                            <thead>
                                            <tr>
                                                <th style="width: 10%">Código</th>
                                                <th style="width: 40%">Nome</th>
                                                <th style="width: 20%">CPF</th>
                                                <th style="width: 12%">Especialidade</th>
                                                <th style="width: 7%">Ações</th>
                                            </tr>
                                            </thead>
                                            <tbody>

                                            <tr>
                                                <td>11</td>
                                                <td>Adib Jatene</td>
                                                <td>03801005097</td>
                                                <td>Clinico geral</td>
                                                <td>
                                                    <a href="#" class="btn btn-info btn-xs">
                                                        <i class="fa fa-pencil"></i>
                                                    </a>
                                                    <a href="javascript:void(0);" data-url="#" class="btn btn-danger btn-xs fconfirma">
                                                        <i class="fa fa-trash"></i>
                                                    </a>
                                                </td>
                                            </tr>

                                            <tr>
                                                <td>12</td>
                                                <td>Bernardino Ramazzini</td>
                                                <td>29654870002</td>
                                                <td>Dentista</td>
                                                <td>
                                                    <a href="#" class="btn btn-info btn-xs">
                                                        <i class="fa fa-pencil"></i>
                                                    </a>
                                                    <a href="javascript:void(0);" data-url="#" class="btn btn-danger btn-xs fconfirma">
                                                        <i class="fa fa-trash"></i>
                                                    </a>
                                                </td>
                                            </tr>

                                            <tr>
                                                <td>13</td>
                                                <td>Carlos Chagas</td>
                                                <td>15155434041</td>
                                                <td>Pediatra</td>
                                                <td>
                                                    <a href="#" class="btn btn-info btn-xs">
                                                        <i class="fa fa-pencil"></i>
                                                    </a>
                                                    <a href="javascript:void(0);" data-url="#" class="btn btn-danger btn-xs fconfirma">
                                                        <i class="fa fa-trash"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </section>
            </div>
            <div class="box">
                <section class="content-header">

                    <div class="box-header">
                        <h3>Paciente</h3>
                    </div>
                    <div class="p-3">
                        <div class="row" >
                            <div class="col-md-5">
                                <a href="{% url 'core:cadastro_par' %}" type="button" class="btn btn-fw primary">Novo</a>
                            </div>
                            <div class="col-sm-4">
                            </div>
                            <div class="col-sm-3">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Busca" style="background: none;margin: -3px 5px 0px 0px;">
                                    <span class="input-group-btn">
              <button class="btn white" type="button">Go!</button>
            </span>
                                </div>
                            </div>
                        </div>
                    </div>

                </section>
                <!-- Main content -->
                <section class="content" style="padding-top: 0">
                    <div id="main-wrapper">
                        <div class="col-lg-12 col-md-12">
                            <div class="panel panel-white">
                                <div class="panel-body">
                                    <div class="">
                                        <table id="example" class="display table bootstrap-grid" style="width: 100%;">
                                            <thead>
                                            <tr>
                                                <th style="width: 10%">Código</th>
                                                <th style="width: 40%">Nome</th>
                                                <th style="width: 20%">CPF</th>
                                                <th style="width: 12%">Nascimento</th>
                                                <th style="width: 7%">Ações</th>
                                            </tr>
                                            </thead>
                                            <tbody>

                                            <tr>
                                                <td>11</td>
                                                <td>Teste</td>
                                                <td>00</td>
                                                <td>2</td>
                                                <td>
                                                    <a href="#" class="btn btn-info btn-xs">
                                                        <i class="fa fa-pencil"></i>
                                                    </a>
                                                    <a href="javascript:void(0);" data-url="#" class="btn btn-danger btn-xs fconfirma">
                                                        <i class="fa fa-trash"></i>
                                                    </a>
                                                </td>
                                            </tr>

                                            <tr>
                                                <td>12</td>
                                                <td>Teste 2</td>
                                                <td>04</td>
                                                <td>1</td>
                                                <td>
                                                    <a href="#" class="btn btn-info btn-xs">
                                                        <i class="fa fa-pencil"></i>
                                                    </a>
                                                    <a href="javascript:void(0);" data-url="#" class="btn btn-danger btn-xs fconfirma">
                                                        <i class="fa fa-trash"></i>
                                                    </a>
                                                </td>
                                            </tr>

                                            <tr>
                                                <td>3</td>
                                                <td>Teste</td>
                                                <td>00</td>
                                                <td>1</td>
                                                <td>
                                                    <a href="#" class="btn btn-info btn-xs">
                                                        <i class="fa fa-pencil"></i>
                                                    </a>
                                                    <a href="javascript:void(0);" data-url="#" class="btn btn-danger btn-xs fconfirma">
                                                        <i class="fa fa-trash"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </section>
            </div>
        </div>
        <!-- ############ Main END-->
    </div>
{% endblock %}

agiosaude/core/templates/home.html
{% extends "base.html" %}

{% load static %}

{% block home %}
    <div class="header" style="font-family: sans-serif">
        <div class="home-menu pure-menu pure-menu-open pure-menu-horizontal pure-menu-fixed">
            <img src="{% static 'arq/logo_hor.png' %}" width="200px"/>
            <ul style="margin: 6px 0px 0px 0px">
                <li class="pure-menu-selected"><a href="{% url 'core:home' %}">Início</a></li>
                {# tela de cadastro de medico/paciente#}
                <li><a href="{% url 'core:cadastro_main' %}">Cadastro</a></li>
                {# tela de cadastro parcial da "Consulta"(paciente, horario da solicitação, medico)#}
                <li><a href="{% url 'core:atendimento_main' %}">Atendimento</a></li>
                {# tela de prencimento da "Consulta" pelo medico("Laudos", "Exames", "Receitas", horario do atendimento, ...)#}
                <li><a href="{% url 'core:consulta_main' %}">Consultório</a></li>
                {# tela de consulta e baixa de "Receitas"#}
                <li><a href="{% url 'core:ambulatorio_main' %}">Ambulatório</a></li>
                {# tela de relatorios#}
                <li>
                    <div class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">Registros</a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="background-color: #56baed">
                            <a class="dropdown-item" href="{% url 'core:registro_ate' %}">Atendimentos</a>
                            <a class="dropdown-item" href="{% url 'core:registro_exa' %}">Exames</a>
                        </div>
                    </div>

                </li>
                {# tela de cadastro de Usuários#}
                <li>
                    <div class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">Sistema</a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="background-color: #56baed">
                            <a href="{% url 'accounts:usuario_main' %}">Usuário</a>
                            <a href="{% url 'accounts:hospital' %}">Hospital</a>
                        </div>
                    </div>
                </li>
                <li><a href="{% url 'accounts:logout' %}">Sair</a></li>
            </ul>
        </div>
    </div>
{% endblock %}

agiosaude/core/templates/login.html
{% extends "base.html" %}

{% load static %}
{% block home %}
    <div class="wrapper fadeInDown">
        <div id="formContent">
            <!-- Tabs Titles -->

            <!-- Icon -->
            <div class="fadeIn first">
                <img src="{% static 'arq/logo_ver.png' %}" id="icon" alt="User Icon" />
            </div>

            <!-- Login Form -->
            <form method="post">
                {% csrf_token %}
                <fieldset>
                    {{ form.non_field_errors }}

                    {% for field in form %}
                        <div class="fadeIn fourth">
                            {{ field.label_tag }}
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    {% endfor %}
                    <input type="submit" class="fadeIn fourth">
                </fieldset>
            </form>
            <!-- Remind Passowrd -->
            <div id="formFooter">
                <a class="underlineHover" href="#">Forgot Password?</a>
            </div>
        </div>
    </div>
{% endblock %}