agiosaude/accounts/urls.py
from django.urls import path
from agiosaude.accounts import views as acc_view
from django.contrib.auth import views as auth_view

urlpatterns = [
    path('', auth_view.LoginView.as_view(template_name='login.html'), name='login'),
    path('sair/', auth_view.LogoutView.as_view(next_page='core:home'), name='logout'),
    path('usuario/', acc_view.Usuario_Main, name='usuario_main'),
    path('usuario/novo', acc_view.usuario_nov, name='usuario_nov'),
    path('hospital/', acc_view.edit, name='hospital')
]

agiosaude/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('agiosaude.core.urls', 'core'), namespace='core')),
    path('login/', include(('agiosaude.accounts.urls', 'accounts'), namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agiosaude/accounts/models.py
import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin, UserManager)
from django.conf import settings


class User(AbstractBaseUser, PermissionsMixin):
    fun_choiche = (
        ('M', 'Médico'),
        ('A', 'Atendente'),
        ('E', 'Enfermeiro'),
        ('F', 'Farmaceutico'),
        ('S', 'Administrador'),
    )

    username = models.CharField(
        'Usuário', max_length=30, unique=True,
        validators=[validators.RegexValidator(re.compile('^[\w.@+-]+$'),
            'O nome de usuário só pode conter letras, digitos ou os '
            'seguintes caracteres: @/./+/-/_', 'invalid')]
    )
    email = models.EmailField('E-mail', unique=True)
    name = models.CharField('Nome', max_length=100)
    funcao = models.CharField('Função', choices=fun_choiche, max_length=1)
    is_active = models.BooleanField('Está ativo?', blank=True, default=True)
    is_staff = models.BooleanField('É da equipe?', blank=True, default=False)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

agiosaude/core/models.py
from django.db import models


class Hospital(models.Model):
    uf_choiche = (
        ('AC', 'Acre'),
        ('AL', 'Alagoas'),
        ('AP', 'Amapá'),
        ('AM', 'Amazonas'),
        ('BA', 'Bahia'),
        ('CE', 'Ceará'),
        ('DF', 'Distrito Federal'),
        ('ES', 'Espírito Santo'),
        ('GO', 'Goiás'),
        ('MA', 'Maranhão'),
        ('MT', 'Mato Grosso'),
        ('MS', 'Mato Grosso do Sul'),
        ('MG', 'Minas Gerais'),
        ('PA', 'Pará'),
        ('PB', 'Paraíba'),
        ('PR', 'Paraná'),
        ('PE', 'Pernambuco'),
        ('PI', 'Piauí'),
        ('RJ', 'Rio de Janeiro'),
        ('RN', 'Rio Grande do Norte'),
        ('RS', 'Rio Grande do Sul'),
        ('RO', 'Rondônia'),
        ('RR', 'Roraima'),
        ('SC', 'Santa Catarina'),
        ('SP', 'São Paulo'),
        ('SE', 'Sergipe'),
        ('TO', 'Tocantins'),
    )
    razao = models.CharField('Razão Social', max_length=100)
    fantasia = models.CharField('Nome Fantasia', max_length=100, null=True, blank=True)
    cnpj = models.IntegerField('CNPJ', null=True, blank=True)
    logo = models.ImageField(verbose_name='Logomarca', null=True, blank=True)
    cep = models.IntegerField('CEP')
    logradouro = models.CharField('Logradouro', max_length=200)
    num_end = models.IntegerField('Numero', null=True, blank=True)
    bairro = models.CharField('Bairro', max_length=100)
    municipio = models.CharField('Municipio', max_length=100)
    uf = models.CharField('UF', choices=uf_choiche, max_length=2)
    cnes = models.IntegerField('CNES')


class Paciente(models.Model):
    sexo_choiche = (
        ('M', 'Masculino'),
        ('F', 'Feminino'),
    )
    uf_choiche = (
        ('AC', 'Acre'),
        ('AL', 'Alagoas'),
        ('AP', 'Amapá'),
        ('AM', 'Amazonas'),
        ('BA', 'Bahia'),
        ('CE', 'Ceará'),
        ('DF', 'Distrito Federal'),
        ('ES', 'Espírito Santo'),
        ('GO', 'Goiás'),
        ('MA', 'Maranhão'),
        ('MT', 'Mato Grosso'),
        ('MS', 'Mato Grosso do Sul'),
        ('MG', 'Minas Gerais'),
        ('PA', 'Pará'),
        ('PB', 'Paraíba'),
        ('PR', 'Paraná'),
        ('PE', 'Pernambuco'),
        ('PI', 'Piauí'),
        ('RJ', 'Rio de Janeiro'),
        ('RN', 'Rio Grande do Norte'),
        ('RS', 'Rio Grande do Sul'),
        ('RO', 'Rondônia'),
        ('RR', 'Roraima'),
        ('SC', 'Santa Catarina'),
        ('SP', 'São Paulo'),
        ('SE', 'Sergipe'),
        ('TO', 'Tocantins'),
    )
    raca_choiche = (
        ('BA', 'Branca'),
        ('NE', 'Negro'),
        ('AM', 'Amarela'),
        ('PA', 'Parda'),
        ('IN', 'Indígena'),
        ('OU', 'Outra'),
        ('ND', 'Não Declarado'),
    )
    name = models.CharField('Nome', max_length=100)
    rg = models.IntegerField('RG', null=True, blank=True)
    uf_nas = models.CharField('UF', choices=uf_choiche, max_length=2, null=True, blank=True)
    pai = models.CharField('Pai', max_length=100, blank=True, null=True)
    mae = models.CharField('Mãe', max_length=100, blank=True, null=True)
    slug = models.SlugField('Atalho')
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    foto = models.ImageField(upload_to='', verbose_name='Foto', null=True, blank=True)
    cpf = models.IntegerField('CPF', null=True, blank=True)
    nascimento = models.DateField('Nascimento')
    sexo = models.CharField('Sexo', choices=sexo_choiche, max_length=1)
    profissao = models.CharField('Profissão', max_length=100, blank=True, null=True)
    telefone = models.IntegerField('Contato', null=True, blank=True)
    cep = models.IntegerField('CEP', null=True, blank=True)
    logradouro = models.CharField('Logradouro', max_length=100, blank=True, null=True)
    bairro = models.CharField('Logradouro', max_length=100, blank=True, null=True)
    municipio = models.CharField('Municipio', max_length=100, blank=True, null=True)
    uf_end = models.CharField('UF', choices=uf_choiche, max_length=2)
    ibge = models.IntegerField('IBGE', null=True, blank=True)
    raca = models.CharField('Raça', choices=raca_choiche, max_length=2)
    etnia = models.CharField('Etnia', max_length=50, blank=True, null=True)

    class Meta:
        verbose_name = 'Paciente'
        verbose_name_plural = 'Pacientes'
        ordering = ['name']


class Funcionario(models.Model):
    sexo_choiche = (
        ('M', 'Masculino'),
        ('F', 'Feminino'),
    )
    fun_choiche = (
        ('M', 'Médico'),
        ('A', 'Atendente'),
        ('E', 'Enfermeiro'),
        ('F', 'Farmaceutico'),
    )
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Atalho')
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    foto = models.ImageField(upload_to='', verbose_name='Foto', null=True, blank=True)
    cpf = models.IntegerField('CPF', null=True, blank=True)
    nascimento = models.DateField('Nascimento', null=True, blank=True)
    sexo = models.CharField('Sexo', choices=sexo_choiche, max_length=1)
    funcao = models.CharField('Função', choices=fun_choiche, max_length=1)
    profissao = models.CharField('Profissão', max_length=100, null=True, blank=True)

    class Meta:
        verbose_name = 'Funcionário'
        verbose_name_plural = 'Funcionários'
        ordering = ['name']


class Medicamento(models.Model):
    name = models.CharField('Nome', max_length=100)
    description = models.TextField('Descrição', blank=True)
    slug = models.SlugField('Atalho')
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    quatidade = models.IntegerField('Quatidade')

    class Meta:
        verbose_name = 'Medicamento'
        verbose_name_plural = 'Medicamentos'
        ordering = ['name']


class Laudo(models.Model):
    description = models.TextField('Descrição', blank=True)
    slug = models.SlugField('Atalho')
    paciente = models.ForeignKey(Paciente, verbose_name='Paciente', on_delete=models.CASCADE, related_name='laudo_par')
    funcionario = models.ForeignKey(Funcionario, verbose_name='Funcionário', on_delete=models.CASCADE, related_name='laudo_fun')

    class Meta:
        verbose_name = 'Laudo'
        verbose_name_plural = 'Laudos'
        ordering = ['paciente']


class Atendimento(models.Model):
    cla_choiche = (
        ('AZ', 'Azul'),
        ('VD', 'Verde'),
        ('AM', 'Amarelo'),
        ('VM', 'Vermelho'),
    )
    trazido_choiche = (
        ('CP', 'Condução Própria'),
        ('AM', 'Ambulância'),
        ('SB', 'Samu/Bombeiro'),
        ('PV', 'Policiais e Viaturas'),
    )
    ficha = models.IntegerField('Ficha')
    classificacao = models.CharField('Classificação', choices=cla_choiche, max_length=2)
    senha = models.IntegerField('Senha', null=True, blank=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    termino = models.DateTimeField('Término', null=True, blank=True)
    paciente = models.ForeignKey(Paciente, verbose_name='Paciente', on_delete=models.CASCADE, related_name='ate_par')
    funcionario = models.ForeignKey(Funcionario, verbose_name='Funcionário', on_delete=models.CASCADE, related_name='ate_fun')
    primeiro = models.BooleanField('Primeiro Atendimento')
    acidente_trab = models.BooleanField('Acidente de trabalho')
    trazido = models.CharField('Trazido por', choices=trazido_choiche, max_length=1)
    acompanhante = models.CharField('Acompanhante', max_length=100, null=True, blank=True)
    placa = models.CharField('Placa da Viatura', max_length=20, null=True, blank=True)
    pressao = models.CharField('Pressão Arterial', max_length=20, null=True, blank=True)
    temperatura =  models.IntegerField('Temperatura', null=True, blank=True)
    peso = models.IntegerField('Peso', blank=True, null=True)
    altura = models.IntegerField('Peso', blank=True, null=True)
    dextro = models.BooleanField('Dextro')
    descricao = models.TextField('Descrição', null=True, blank=True)
    hipotese = models.TextField('Hipótese Diagnostica', null=True, blank=True)
    conduta = models.TextField('Condulta', null=True, blank=True)
    anotacoes = models.TextField('Anotações', null=True, blank=True)


class Procedimento(models.Model):
    atendimento = models.ForeignKey(Atendimento, verbose_name='Atendimento', on_delete=models.CASCADE, related_name='pro_atende')
    procedimento = models.IntegerField('Procedimento')
    quantidade = models.IntegerField('Quantidade')
    cbo = models.IntegerField('CBO', null=True, blank=True)
    cid = models.IntegerField('CID', null=True, blank=True)
    carater_atend = models.IntegerField('Carater Atendimento', null=True, blank=True)
    autorizacao = models.IntegerField('Número Autorização', null=True, blank=True)


class Exame(models.Model):
    atendimento = models.ForeignKey(Atendimento, verbose_name='Atendimento', on_delete=models.CASCADE, related_name='exa_atende')
    descricao = models.TextField('Descrição')
    data = models.DateField ('Data de entrega', null=True, blank=True)
    realizado = models.BooleanField('Concluido')
    resultado = models.TextField('Resultado', null=True, blank=True)
    anexo = models.FileField(upload_to='core/static/arq', blank=True, null=True)
    # anexo = models.TextField('File', blank=True)

agiosaude/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from agiosaude.core import models

from agiosaude.core.mail import send_mail_template

class EditHospitalForm(forms.ModelForm):

    class Meta:
        model = models.Hospital
        fields = ['razao', 'fantasia', 'cnpj', 'cep', 'logradouro',
                  'num_end', 'bairro', 'municipio', 'uf', 'cnes']

agiosaude/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from .forms import EditHospitalForm
from agiosaude.core.models import *
from agiosaude.accounts.models import User
from django.contrib import messages

# Create your views here.
@login_required
def Usuario_Main(request):
    usuarios = User.objects.all()
    template_name = 'usuario_main.html'
    context ={'usuarios':usuarios}
    return render()

@login_required
def usuario_nov(request):
    return render(request, 'usuario_nov.html')

@login_required
def edit(request):
    obj = get_object_or_404(Hospital, pk=1)
    template_name = 'hospital.html'
    context = {}
    if request.method == 'POST':
        form = EditHospitalForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            messages.success(request, 'Os dados foram atualizados com sucesso!')
            return redirect('core:home')
    else:
        form = EditHospitalForm(instance=obj)
    context['form'] = form
    return render(request, template_name, context)

agiosaude/accounts/templates/hospital.html
{% extends 'home.html' %}
{% load static %}
{% block content %}
    <div class="content-main " id="content-main">
        <!-- ############ main start-->
        <div class="padding">
            <div class="box">
                <section class="content-header">
                    <div class="page-title">
                        <div class="page-breadcrumb">
                            <ol class="breadcrumb" style="padding: 2px 0px 0px 15px">
                                <li class="active" style="font-size: 20px">Dados Hospitalar</li>
                            </ol>
                        </div>
                    </div>
                </section>
                <section class="content" style="padding: 0">
                    <div id="main-wrapper">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="box-header">
                                    <div class="panel-body">
                                        <form class="pure-form pure-form-stacked" method="post">
                                            {% csrf_token %}
                                            <fieldset>
                                                {{ form.non_field_errors }}
                                                <div class="row">
                                                    {% for field in form %}
                                                        <div style="margin-left: 15px;">
                                                            <div class="form-group">
                                                                {{ field.label_tag }}
                                                                {{ field }}
                                                                {{ field.errors }}
                                                            </div>
                                                        </div>
                                                    {% endfor %}
                                                </div>
                                                <div class="pure-controls">
                                                    <button type="submit" class="btn btn-outline b-success text-success">Salvar</button>
                                                    <a href="{% url 'core:home' %}" class="btn btn-outline b-warning text-warning">Cancelar</a>
                                                </div>
                                            </fieldset>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
{% endblock %}

agiosaude/accounts/templates/usuario_main.html
{% extends 'home.html' %}
{% load static %}

{% block content %}
    <div class="content-main " id="content-main">
        <!-- ############ Main START-->
        <div class="padding">
            <div class="box">
                <section class="content-header">
                    <div class="box-header">
                        <h3>Registro de Usuários</h3>
                    </div>
                    <div class="p-3">
                        <div class="row" >
                            <div class="col-md-5">
                                <a href="{% url 'accounts:usuario_nov' %}" type="button" class="btn btn-fw primary">Novo</a>
                            </div>
                            <div class="col-sm-4">
                            </div>
                            <div class="col-sm-3">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Busca" style="background: none;margin: -3px 5px 0px 0px;">
                                    <span class="input-group-btn">
                                        <button class="btn white" type="button">Go!</button>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>

                </section>
                <!-- Main content -->
                <section class="content" style="padding-top: 0">
                    <div id="main-wrapper">
                        <div class="col-lg-12 col-md-12">
                            <div class="panel panel-white">
                                <div class="panel-body">
                                    <div class="">
                                        <table id="example" class="display table bootstrap-grid" style="width: 100%;">
                                            <thead>
                                            <tr>
                                                <th style="width: 40%">Usuário</th>
                                                <th style="width: 20%">Nome</th>
                                                <th style="width: 12%">Função</th>
                                                <th style="width: 7%">Ultimo Acesso</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for usuario in object_list %}
                                                <tr>
                                                    <td>{{ usuario.username }}</td>
                                                    <td>{{ usuario.name }}</td>
                                                    <td>{{ usuario.funcao }}</td>
                                                    <td>{{ usuario.date_joined }}</td>
                                                    <td>
                                                        <a href="#" class="btn btn-info btn-xs">
                                                            <i class="fa fa-pencil"></i>
                                                        </a>
                                                        <a href="javascript:void(0);" data-url="#" class="btn btn-danger btn-xs fconfirma">
                                                            <i class="fa fa-trash"></i>
                                                        </a>
                                                    </td>
                                                </tr>
                                            {% empty %}
                                                <li>Sem usuarios</li>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </section>
            </div>
        </div>
    </div>
{% endblock %}

agiosaude/accounts/templates/usuario_nov.html
{% extends 'home.html' %}
{% load static %}
{% block content %}
    <div class="content-main " id="content-main">
        <!-- ############ main start-->
        <div class="padding">
            <div class="box">
                <section class="content-header">
                    <div class="page-title">
                        <div class="page-breadcrumb">
                            <ol class="breadcrumb" style="padding: 2px 0px 0px 15px">
                                <li class="active" style="font-size: 20px">Novo Usuário</li>
                            </ol>
                        </div>
                    </div>
                </section>
                <!-- main content -->
                <section class="content" style="padding: 0">
                    <div id="main-wrapper">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="box-header">
                                    <div class="panel-body">
                                        <form action="" method="post" enctype="multipart/form-data" class="input_mask" novalidate="">
                                            <input type="hidden" name="csrfmiddlewaretoken" value="cycgtyfkjrufvcggplzzzjbnj59sfnv4nkjqwslzidt15rgotevooo5s8zf31bfj">
                                            <div class="row">
                                                <div style="width:auto; height:auto;margin-left: 15px;">
                                                    <div class="form-group">
                                                        <label class="control-label  " for="id_descricao" style="margin: 0">Login*</label>
                                                        <div class=" ">
                                                            <input type="text" name="descricao" maxlength="100" class=" form-control" required="" id="id_descricao">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div style="width:auto; height:auto;margin-left: 15px;">
                                                    <div class="form-group">
                                                        <label class="control-label  " for="id_sindicato" style="margin: 0">Senha Inicial*</label>
                                                        <div class=" ">
                                                            <input type="text" name="cbo" maxlength="11" class="num form-control" required="" id="id_cbo" autocomplete="off">
                                                        </div>
                                                    </div>
                                                </div>
                                                    <div class="form-group">
                                                        <label class="control-label  " for="id_tipo_criacao" style="margin: 0">Função de Acesso*</label>
                                                        <div class=" ">
                                                            <select name="tipo_criacao" class=" form-control" required="" id="id_tipo_criacao">
                                                                <option value="" selected="">---------</option>
                                                                <option value="decreto">Masculino</option>
                                                                <option value="decreto">Feminino</option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                            <div class="form-group">
                                                <div class="">
                                                    <button type="submit" class="btn btn-outline b-success text-success"><i></i>Salvar</button>
                                                    <a href="{% url 'accounts:usuario_main' %}" class="btn btn-outline b-warning text-warning">Cancelar</a>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </section>
            </div>
        </div>
        <!-- ############ main end-->
    </div>
{% endblock %}